export const genders = ['Male', 'Female', 'Other'];

export const sortings = ['Timeframe', 'Skill Level', 'Region'];

export const ratings = [
  '1.0 - Beginner',
  '2.0 - Limited Experience',
  '3.0 - Intermediate',
  '4.0 - Advanced',
  '5.0 - Professional',
];

export const regions = [
  'Adams-Normandie',
  'Alsace',
  'Angelino Heights',
  'Arleta',
  'Arlington Heights',
  'Arlington Park',
  'Atwater Village',
  'Baldwin Hills',
  'Bel Air',
  'Berkeley Square',
  'Beverly Crest',
  'Beverly Glen',
  'Beverlywood',
  'Boyle Heights',
  'Brentwood',
  'Brookside',
  'Byzantine-Latino Quarter',
  'Cadillac-Corning',
  'Cahuega Pass',
  'Cahuenga Pass',
  'Canoga Park',
  'Carthay',
  'Castle Heights',
  'Central City East',
  'Central-Alameda',
  'Century City',
  'Century Palms/Cove',
  'Chatsworth',
  'Cheviot Hills',
  'Chinatown/Historic LA',
  'Cloverdale/Cochran',
  'Country Club Heights',
  'Country Club Park',
  'Crenshaw',
  'Crenshaw Manor',
  'Crestview',
  'Cypress Park',
  'Del Rey',
  'Downtown LA',
  'Eagle Rock',
  'East Hollywood',
  'Echo Park',
  'El Sereno',
  'Elysian Park',
  'Elysian Valley',
  'Encino',
  'Exposition Park',
  'Faircrest Heights',
  'Fairfax',
  'Figueroa Park Square',
  'Florence-Firestone',
  'Franklin Village',
  'Fremont Place',
  'Glassell Park',
  'Gramercy Park',
  'Granada Hills',
  'Green Meadows',
  'Griffith Park',
  'Hancock Park',
  'Hansen Dam Rec Area',
  'Harbor City',
  'Harbor Gateway',
  'Harbor Pines',
  'Harvard Heights',
  'Harvard Park',
  'Hermon',
  'Hidden Village',
  'Highland Park',
  'Historic Filipinotown',
  'Historic West Adams',
  'Hollywood',
  'Hollywood Hills',
  'Hyde Park',
  'Jefferson Park',
  'King Estates',
  'Kinney Heights',
  'Koreatown',
  'L.A.International Airport',
  'La Brea Hancock',
  'La Tuna Canyon',
  'Lafayette Square',
  'Lake Balboa',
  'Lakeview Terrace',
  'Larchmont Village',
  'Leimert Park',
  'Lincoln Heights',
  'Little Armenia',
  'Little Bangladesh',
  'Little Tokyo',
  'Longwood',
  'Los Feliz',
  'Manchester Square',
  'Mandeville Canyon',
  'Maplewood-St. Andrews',
  'Mar Vista',
  'Marina Peninsula',
  'Melrose',
  'Melrose Hill',
  'Mid-City',
  'Mid-City West',
  'Mid-Wilshire',
  'Miracle Mile',
  'Mission Hills',
  'Montecito Heights',
  'Monterey Hills',
  'Mt. Washington',
  'North Hills',
  'North Hollywood',
  'Northridge',
  'Olympic Park',
  'Pacific Palisades',
  'Pacoima',
  'Palisades Highlands',
  'Palms',
  'Panorama City',
  'Park La Brea',
  'Picfair Village',
  'Pico Park',
  'Pico Union',
  'Playa Vista',
  'Playa del Rey',
  'Porter Ranch',
  'Rampart Village',
  'Rancho Park',
  'Redondo Sycamore',
  'Regent Square',
  'Reseda',
  'Reseda Ranch',
  'Reynier Village',
  'San Pedro',
  'Sawtelle',
  'Shadow Hills',
  'Sherman Oaks',
  'Silver Lake',
  'South Carthay',
  'South Park',
  'South Robertson',
  'St. Andrews Square',
  'St. Elmo Village',
  'Studio City',
  'Sugar Hill',
  'Sun Valley',
  'Sunland',
  'Sycamore Grove',
  'Sycamore Square',
  'Sylmar',
  'Tarzana',
  'Temple-Beaudry',
  'Terminal Island',
  'Thai Town',
  'Toluca Lake',
  'Toluca Terrace',
  'Toluca Woods',
  'Topanga State Park',
  'Tujunga',
  'University Expo Park West',
  'University Hills',
  'University Park',
  'Valley Glen',
  'Valley Village',
  'Van Nuys',
  'Venice',
  'Vermont Knolls',
  'Vermont Square',
  'Vermont Vista',
  'Vernon Central',
  'Victoria Park',
  'View Heights',
  'Watts',
  'Wellington Square',
  'West Adams',
  'West Adams Heights',
  'West Adams Terrace',
  'West Hills',
  'West Los Angeles',
  'West Toluca Lake',
  'West Vernon',
  'Westchester/LAX',
  'Western Heights',
  'Western Wilton',
  'Westlake',
  'Westside Village',
  'Westwood',
  'Wholesale District',
  'Wilmington',
  'Wilshire Center',
  'Wilshire Park',
  'Wilshire Vista',
  'Wilshire Vista Heights',
  'Windsor Square',
  'Windsor Village',
  'Winnetka',
  'Woodland Hills',
];
